**python**

In [ ]:
# 1
lst = ["aman", "222", 777, 400.4]
print(tuple(lst))

In [ ]:
# 2
import datetime
dct = {
  "rollno": 1,
  "lname": "b",
  "fname": "a",
  "dob": str(datetime.datetime(2000, 6, 1))
}

print(dct)


In [ ]:
# 3
import numpy as np

np.random.seed(42)
arr = np.random.randint(1,10,size=(2,2))
print(arr)

[[7 4]
 [8 5]]


In [ ]:
# 4. Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
import random

print(random.randint(0,1))
print(random.uniform(0,1))

print(abs(-1234))


0
0.4404233903060386
1234


In [ ]:
# 5
import random

print(random.randint(20,90))

49


In [ ]:
# 6
import random
arr = [11, 12, 13,14, 15]

print(random.sample(arr,3))

newarr = random.shuffle(arr)
print(newarr)


print(arr[ random.randint(0,len(arr)-1) ])

[15, 14, 12]
None
13


In [ ]:

# 7
f = open("file.txt","w")
f.write("The King is Dead, Long Live The King")
f.close()


In [ ]:
# 8
i = 10
while i:
  i -= 1
  print("-",end="")
  continue  
  print("a")

print()

In [ ]:
# 9

print("The King is Dead, Long Live The King"[2:5])
print("The King is Dead, Long Live The King".split())

In [ ]:
# 10
import numpy as np

lst = [1,4,5,8]
arr = np.array(lst, dtype="f")
print(arr[:2],arr[2:])


[1. 4.] [5. 8.]


In [ ]:
# 11
a1 = [1,2,3]
a2 = [4,5,6]

arr2d = np.array([a1,a2],dtype='f')
print(arr2d)

In [ ]:
# 12
import numpy
arr = np.array([[1,2,3],[4,5,6]])

print(arr[1,:])

print( arr[:,1].astype(numpy.float32) )

print("length =",arr.size)

[4 5 6]
[2. 5.]
length = 6


In [ ]:
# 13
import numpy as np  

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = arr.reshape(5,2)
print(arr2)
print(arr2.T)


In [ ]:
# 14
import numpy as np  
lst = [1,2,3]
arr = np.array(lst)
print(arr)

In [ ]:
# 15 Fill an array [1,2,3] with a single value [9,9,9]. 
arr = np.array([1,2,3])

for _ in range(len(arr)): arr = arr * 0 + 9
print(arr)

[9 9 9]


In [ ]:
# 16
import numpy as np  

arr1 = np.array([2,4,5])
print(arr1.sum())

In [ ]:
# 17
import numpy as np  

arr1 = np.array([77,74,75])
print(arr1.prod())

In [ ]:
# 18
import numpy as np  

arr1 = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("mean",arr1.mean())
print("variance",arr1.var())

print("min",arr1.min())
print("max",arr1.max())

print("argmin",arr1.argmin())
print("median",np.median(arr1) )
print("argmax",arr1.argmax())

print("standard deviation",arr1.std())

In [ ]:
# 19
import numpy as np  

arr = np.array([2,1,1,4,5,5,5,7])
arr_unique = np.unique(arr)
print(arr_unique) # unique automatically sorts it, but you can use np.sort(arr) to sort elements

In [ ]:
# 20
import numpy as np  

arr1 = np.array([1,2,3])
arr2 = np.array([0,1,1])

arr_dotprod = np.dot(arr1,arr2)

print(arr_dotprod)

In [ ]:
# 21
import numpy as np  

arr = np.array([ [2, -12],[1, -5] ])
eig = np.linalg.eig(arr)
print("eigenvalue", eig[0])
print("eigenvector", eig[1])

In [ ]:
# 22

arr1 = np.array([11, 22, 11, 31])
arr2 = np.array([25, 33, 31, 28])
  
# pearson product-moment correlation
# coefficients of the arrays
rslt = np.corrcoef(arr1, arr2)
  
print(rslt)

[[1.         0.15997968]
 [0.15997968 1.        ]]
